//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worker_7ERFAcraft.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Worker_7ERFAcraft.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want a delivery service to the client&apos;s house..
        /// </summary>
        internal static string AcceptOptionOne {
            get {
                return ResourceManager.GetString("AcceptOptionOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I do not want a delivery service to the client&apos;s house..
        /// </summary>
        internal static string AcceptOptionTwo {
            get {
                return ResourceManager.GetString("AcceptOptionTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please accept the terms &amp; conditions.
        /// </summary>
        internal static string AcceptTerms {
            get {
                return ResourceManager.GetString("AcceptTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to accept this order?.
        /// </summary>
        internal static string AcceptThisOrder {
            get {
                return ResourceManager.GetString("AcceptThisOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Balance.
        /// </summary>
        internal static string AddBalance {
            get {
                return ResourceManager.GetString("AddBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Details.
        /// </summary>
        internal static string AddDetails {
            get {
                return ResourceManager.GetString("AddDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree with .
        /// </summary>
        internal static string AgreeWithTerms {
            get {
                return ResourceManager.GetString("AgreeWithTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        internal static string AlreadyhaveAccount {
            get {
                return ResourceManager.GetString("AlreadyhaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Sent.
        /// </summary>
        internal static string AlreadySent {
            get {
                return ResourceManager.GetString("AlreadySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Video.
        /// </summary>
        internal static string AppVideo {
            get {
                return ResourceManager.GetString("AppVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        internal static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available for Job?.
        /// </summary>
        internal static string AvailableForJob {
            get {
                return ResourceManager.GetString("AvailableForJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bangali.
        /// </summary>
        internal static string Bangali {
            get {
                return ResourceManager.GetString("Bangali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator.
        /// </summary>
        internal static string Calculator {
            get {
                return ResourceManager.GetString("Calculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        internal static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel this Order.
        /// </summary>
        internal static string CancelOrder {
            get {
                return ResourceManager.GetString("CancelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Video.
        /// </summary>
        internal static string CaptureVideo {
            get {
                return ResourceManager.GetString("CaptureVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Langauge.
        /// </summary>
        internal static string ChangeLangauge {
            get {
                return ResourceManager.GetString("ChangeLangauge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Users.
        /// </summary>
        internal static string ChatUsers {
            get {
                return ResourceManager.GetString("ChatUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        internal static string choose {
            get {
                return ResourceManager.GetString("choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose civil copy expire date.
        /// </summary>
        internal static string choose_civil_copy_expire_date {
            get {
                return ResourceManager.GetString("choose_civil_copy_expire_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose vehicle form expire date.
        /// </summary>
        internal static string choose_vehicle_form_expire_date {
            get {
                return ResourceManager.GetString("choose_vehicle_form_expire_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose vehicle registration expire date.
        /// </summary>
        internal static string choose_vehicle_registration_expire_date {
            get {
                return ResourceManager.GetString("choose_vehicle_registration_expire_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Cancellation Reason or Enter Other Reason.
        /// </summary>
        internal static string ChooseCancellationReasonorEnterOtherReason {
            get {
                return ResourceManager.GetString("ChooseCancellationReasonorEnterOtherReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Category.
        /// </summary>
        internal static string ChooseCategory {
            get {
                return ResourceManager.GetString("ChooseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose from Gallery.
        /// </summary>
        internal static string ChoosefromGallery {
            get {
                return ResourceManager.GetString("ChoosefromGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Language.
        /// </summary>
        internal static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Photo.
        /// </summary>
        internal static string ChoosePhoto {
            get {
                return ResourceManager.GetString("ChoosePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Photo from Gallery.
        /// </summary>
        internal static string ChoosePhotofromGallery {
            get {
                return ResourceManager.GetString("ChoosePhotofromGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Photo/Video.
        /// </summary>
        internal static string ChoosePhotoVideo {
            get {
                return ResourceManager.GetString("ChoosePhotoVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Reason.
        /// </summary>
        internal static string ChooseReason {
            get {
                return ResourceManager.GetString("ChooseReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Copy of receipt.
        /// </summary>
        internal static string ChooseReceiptImage {
            get {
                return ResourceManager.GetString("ChooseReceiptImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Time From.
        /// </summary>
        internal static string ChooseTimeFrom {
            get {
                return ResourceManager.GetString("ChooseTimeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Time To.
        /// </summary>
        internal static string ChooseTimeTo {
            get {
                return ResourceManager.GetString("ChooseTimeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select if you will Register in as a .
        /// </summary>
        internal static string ChooseUser {
            get {
                return ResourceManager.GetString("ChooseUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to complete this order?.
        /// </summary>
        internal static string CompleteThisOrder {
            get {
                return ResourceManager.GetString("CompleteThisOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed.
        /// </summary>
        internal static string Connectionfailed {
            get {
                return ResourceManager.GetString("Connectionfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Email.
        /// </summary>
        internal static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Phone Numbers.
        /// </summary>
        internal static string ContactPhoneNumbers {
            get {
                return ResourceManager.GetString("ContactPhoneNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy of Civil Register (copy of residencefor non-Saudis and passport).
        /// </summary>
        internal static string CopyofCivilRegister {
            get {
                return ResourceManager.GetString("CopyofCivilRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy of Vehicle Form.
        /// </summary>
        internal static string CopyofVehicleForm {
            get {
                return ResourceManager.GetString("CopyofVehicleForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Account.
        /// </summary>
        internal static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Location.
        /// </summary>
        internal static string CurrentLocation {
            get {
                return ResourceManager.GetString("CurrentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        internal static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum charge of request is 50 SAR..
        /// </summary>
        internal static string CustomerCharge {
            get {
                return ResourceManager.GetString("CustomerCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete chat?.
        /// </summary>
        internal static string DeleteChatConfirm {
            get {
                return ResourceManager.GetString("DeleteChatConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have account?.
        /// </summary>
        internal static string DontHaveAccount {
            get {
                return ResourceManager.GetString("DontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        internal static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to take this service?.
        /// </summary>
        internal static string DriverAcceptRequest {
            get {
                return ResourceManager.GetString("DriverAcceptRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you don&apos;t want to take this service?.
        /// </summary>
        internal static string DriverRejectRequest {
            get {
                return ResourceManager.GetString("DriverRejectRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drivers List.
        /// </summary>
        internal static string DriversList {
            get {
                return ResourceManager.GetString("DriversList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Ride.
        /// </summary>
        internal static string end_ride {
            get {
                return ResourceManager.GetString("end_ride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Amount:.
        /// </summary>
        internal static string EnterAmount {
            get {
                return ResourceManager.GetString("EnterAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Comments.
        /// </summary>
        internal static string EnterComments {
            get {
                return ResourceManager.GetString("EnterComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Details.
        /// </summary>
        internal static string EnterDetails {
            get {
                return ResourceManager.GetString("EnterDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Email.
        /// </summary>
        internal static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Message.
        /// </summary>
        internal static string EnterMessage {
            get {
                return ResourceManager.GetString("EnterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Subject.
        /// </summary>
        internal static string EnterSubject {
            get {
                return ResourceManager.GetString("EnterSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid Email.
        /// </summary>
        internal static string EntervalidEmail {
            get {
                return ResourceManager.GetString("EntervalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Time.
        /// </summary>
        internal static string EstimatedTime {
            get {
                return ResourceManager.GetString("EstimatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to exit the application?.
        /// </summary>
        internal static string ExitApp {
            get {
                return ResourceManager.GetString("ExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can find your new password on above mentioned email or you can contact on this number to get new password.
        /// </summary>
        internal static string ForgotPasswordContactText {
            get {
                return ResourceManager.GetString("ForgotPasswordContactText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter you email address &amp; we will send you an email that you will allow you to reset your password..
        /// </summary>
        internal static string ForgotPasswordString {
            get {
                return ResourceManager.GetString("ForgotPasswordString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Your Password?.
        /// </summary>
        internal static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName or Company Name.
        /// </summary>
        internal static string FullNameorCompanyName {
            get {
                return ResourceManager.GetString("FullNameorCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give at least one star.
        /// </summary>
        internal static string Giveatleastonestar {
            get {
                return ResourceManager.GetString("Giveatleastonestar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Customer.
        /// </summary>
        internal static string GuestCustomer {
            get {
                return ResourceManager.GetString("GuestCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hindi.
        /// </summary>
        internal static string Hindi {
            get {
                return ResourceManager.GetString("Hindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire Me.
        /// </summary>
        internal static string HireMe {
            get {
                return ResourceManager.GetString("HireMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HISTORY.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while trying to connect. Please check your internet and try again..
        /// </summary>
        internal static string InternetMsg {
            get {
                return ResourceManager.GetString("InternetMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number must be start with 0..
        /// </summary>
        internal static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIST.
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Phone Number &amp; Password.
        /// </summary>
        internal static string LoginString {
            get {
                return ResourceManager.GetString("LoginString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to logout?.
        /// </summary>
        internal static string LogoutMsg {
            get {
                return ResourceManager.GetString("LogoutMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will pay %5 of these long order.
        /// </summary>
        internal static string LongOrderPer {
            get {
                return ResourceManager.GetString("LongOrderPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAP.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINUTES.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        internal static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Bookings.
        /// </summary>
        internal static string MyBookings {
            get {
                return ResourceManager.GetString("MyBookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password should not match with old password.
        /// </summary>
        internal static string NewPasswordSameAsOldPassword {
            get {
                return ResourceManager.GetString("NewPasswordSameAsOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Present.
        /// </summary>
        internal static string NoDataPresent {
            get {
                return ResourceManager.GetString("NoDataPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONGOING.
        /// </summary>
        internal static string OnGoing {
            get {
                return ResourceManager.GetString("OnGoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is some error while sending the otp, Please try again later..
        /// </summary>
        internal static string OtpFailureResponse {
            get {
                return ResourceManager.GetString("OtpFailureResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otp Sent Successfully.
        /// </summary>
        internal static string OtpSuccessResponse {
            get {
                return ResourceManager.GetString("OtpSuccessResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP Verification.
        /// </summary>
        internal static string OTPVerification {
            get {
                return ResourceManager.GetString("OTPVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Send to Your Registered Phone Number.
        /// </summary>
        internal static string OTPVerificationString {
            get {
                return ResourceManager.GetString("OTPVerificationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and Confirm Password do not match.
        /// </summary>
        internal static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PENDING.
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number must be of 10 digits..
        /// </summary>
        internal static string PhoneNumberValid {
            get {
                return ResourceManager.GetString("PhoneNumberValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHOTOS &amp; VIDEOS.
        /// </summary>
        internal static string Photos_Videos {
            get {
                return ResourceManager.GetString("Photos_Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose Residency Picture.
        /// </summary>
        internal static string PleaseChooseResidencyPicture {
            get {
                return ResourceManager.GetString("PleaseChooseResidencyPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Balance.
        /// </summary>
        internal static string PleaseEnterBalance {
            get {
                return ResourceManager.GetString("PleaseEnterBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Location.
        /// </summary>
        internal static string PleaseEnterLocation {
            get {
                return ResourceManager.GetString("PleaseEnterLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Name.
        /// </summary>
        internal static string PleaseEnterName {
            get {
                return ResourceManager.GetString("PleaseEnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter new password.
        /// </summary>
        internal static string PleaseEnternewpassword {
            get {
                return ResourceManager.GetString("PleaseEnternewpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter old password.
        /// </summary>
        internal static string PleaseEnteroldpassword {
            get {
                return ResourceManager.GetString("PleaseEnteroldpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Password.
        /// </summary>
        internal static string PleaseEnterpassword {
            get {
                return ResourceManager.GetString("PleaseEnterpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Phone Number.
        /// </summary>
        internal static string PleaseEnterPhoneNumber {
            get {
                return ResourceManager.GetString("PleaseEnterPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Price.
        /// </summary>
        internal static string PleaseEnterPrice {
            get {
                return ResourceManager.GetString("PleaseEnterPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Receipt Number or Choose Receipt Image.
        /// </summary>
        internal static string PleaseEnterReceiptNumberorChooseReceiptImage {
            get {
                return ResourceManager.GetString("PleaseEnterReceiptNumberorChooseReceiptImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Estimated Time.
        /// </summary>
        internal static string PleaseEnterTime {
            get {
                return ResourceManager.GetString("PleaseEnterTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Username.
        /// </summary>
        internal static string PleaseEnterUsername {
            get {
                return ResourceManager.GetString("PleaseEnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate this Order.
        /// </summary>
        internal static string RateOrder {
            get {
                return ResourceManager.GetString("RateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy of receipt.
        /// </summary>
        internal static string ReceiptImage {
            get {
                return ResourceManager.GetString("ReceiptImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Number.
        /// </summary>
        internal static string ReceiptNumber {
            get {
                return ResourceManager.GetString("ReceiptNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reject this order?.
        /// </summary>
        internal static string RejectThisOrder {
            get {
                return ResourceManager.GetString("RejectThisOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residency Number or ID.
        /// </summary>
        internal static string ResidencyNumber {
            get {
                return ResourceManager.GetString("ResidencyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residency Picture or ID Pictures.
        /// </summary>
        internal static string ResidencyPicture {
            get {
                return ResourceManager.GetString("ResidencyPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REVIEWS.
        /// </summary>
        internal static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Category.
        /// </summary>
        internal static string SearchCategory {
            get {
                return ResourceManager.GetString("SearchCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Worker.
        /// </summary>
        internal static string SearchWorker {
            get {
                return ResourceManager.GetString("SearchWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SECONDS.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one Category.
        /// </summary>
        internal static string SelectatleastoneCategory {
            get {
                return ResourceManager.GetString("SelectatleastoneCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Country.
        /// </summary>
        internal static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Month:.
        /// </summary>
        internal static string SelectMonth {
            get {
                return ResourceManager.GetString("SelectMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Service.
        /// </summary>
        internal static string SelectService {
            get {
                return ResourceManager.GetString("SelectService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Price.
        /// </summary>
        internal static string SendQuote {
            get {
                return ResourceManager.GetString("SendQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Feedback.
        /// </summary>
        internal static string ShareFeedback {
            get {
                return ResourceManager.GetString("ShareFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Ride.
        /// </summary>
        internal static string start_ride {
            get {
                return ResourceManager.GetString("start_ride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Photo.
        /// </summary>
        internal static string TakePhoto {
            get {
                return ResourceManager.GetString("TakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        internal static string TermsConditions {
            get {
                return ResourceManager.GetString("TermsConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time From.
        /// </summary>
        internal static string TimeFrom {
            get {
                return ResourceManager.GetString("TimeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time To.
        /// </summary>
        internal static string TimeTo {
            get {
                return ResourceManager.GetString("TimeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Balance:.
        /// </summary>
        internal static string TotalBalance {
            get {
                return ResourceManager.GetString("TotalBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Jobs:.
        /// </summary>
        internal static string TotalJobs {
            get {
                return ResourceManager.GetString("TotalJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again.
        /// </summary>
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        internal static string Unavailable {
            get {
                return ResourceManager.GetString("Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Copy of Civil Register (copy of residencefor non-Saudis and passport).
        /// </summary>
        internal static string UploadCopyofCivilRegister {
            get {
                return ResourceManager.GetString("UploadCopyofCivilRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Vehicle Copy Image.
        /// </summary>
        internal static string UploadvehicleCopyImage {
            get {
                return ResourceManager.GetString("UploadvehicleCopyImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Vehicle Image.
        /// </summary>
        internal static string UploadVehicleImages {
            get {
                return ResourceManager.GetString("UploadVehicleImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urdu.
        /// </summary>
        internal static string Urdu {
            get {
                return ResourceManager.GetString("Urdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Image.
        /// </summary>
        internal static string VehicleImage {
            get {
                return ResourceManager.GetString("VehicleImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        internal static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for the quote (price and estimated time) from the driver..
        /// </summary>
        internal static string WaitingForConfirmation {
            get {
                return ResourceManager.GetString("WaitingForConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Date.
        /// </summary>
        internal static string WorkDate {
            get {
                return ResourceManager.GetString("WorkDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Details.
        /// </summary>
        internal static string WorkDetails {
            get {
                return ResourceManager.GetString("WorkDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker.
        /// </summary>
        internal static string Worker {
            get {
                return ResourceManager.GetString("Worker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker List.
        /// </summary>
        internal static string WorkerList {
            get {
                return ResourceManager.GetString("WorkerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker Profile.
        /// </summary>
        internal static string WorkerProfile {
            get {
                return ResourceManager.GetString("WorkerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work From Date.
        /// </summary>
        internal static string WorkFromDate {
            get {
                return ResourceManager.GetString("WorkFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Hours.
        /// </summary>
        internal static string WorkHours {
            get {
                return ResourceManager.GetString("WorkHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Notes.
        /// </summary>
        internal static string WorkNotes {
            get {
                return ResourceManager.GetString("WorkNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work To Date.
        /// </summary>
        internal static string WorkToDate {
            get {
                return ResourceManager.GetString("WorkToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR DEBT.
        /// </summary>
        internal static string YourDebt {
            get {
                return ResourceManager.GetString("YourDebt", resourceCulture);
            }
        }
    }
}
